services:
    Bref\Symfony\Messenger\Service\BusDriver: '@Bref\Symfony\Messenger\Service\SimpleBusDriver'
    Bref\Symfony\Messenger\Service\SimpleBusDriver:
        arguments:
            - '@logger'
