services:
    Bref\Symfony\Messenger\Service\BusDriver: '@Bref\Symfony\Messenger\Service\SimpleBusDriver'
    Bref\Symfony\Messenger\Service\SimpleBusDriver:
        arguments:
            - '@logger'

    # SNS
    Bref\Symfony\Messenger\Service\Sns\SnsTransportFactory:
        tags: ['messenger.transport_factory']
        autowire: true
    bref.messenger.sns_client:
        class: AsyncAws\Sns\SnsClient
        public: true


    # EventBridge
    Bref\Symfony\Messenger\Service\EventBridge\EventBridgeTransportFactory:
        tags: ['messenger.transport_factory']
        autowire: true
    bref.messenger.eventbridge_client:
        class: AsyncAws\EventBridge\EventBridgeClient
        public: true

