services:
    Bref\Symfony\Messenger\Service\BusDriver: '@Bref\Symfony\Messenger\Service\SimpleBusDriver'
    Bref\Symfony\Messenger\Service\SimpleBusDriver:
        arguments:
            - '@logger'

    Bref\Symfony\Messenger\Service\MessengerTransportConfiguration:
        arguments:
            $messengerTransportsConfiguration: '%messenger.transports%'

    # SNS
    Bref\Symfony\Messenger\Service\Sns\SnsTransportNameResolver:
        arguments:
            - '@Bref\Symfony\Messenger\Service\MessengerTransportConfiguration'
    Bref\Symfony\Messenger\Service\Sns\SnsTransportFactory:
        tags: ['messenger.transport_factory']
        arguments:
            - '@bref.messenger.sns_client'
    bref.messenger.sns_client:
        class: AsyncAws\Sns\SnsClient

    # SQS
    Bref\Symfony\Messenger\Service\Sqs\SqsTransportNameResolver:
        arguments:
            - '@Bref\Symfony\Messenger\Service\MessengerTransportConfiguration'

    # EventBridge
    Bref\Symfony\Messenger\Service\EventBridge\EventBridgeTransportFactory:
        tags: ['messenger.transport_factory']
        arguments:
            - '@bref.messenger.eventbridge_client'
            - '@?bref.messenger.eventbridge_detail_type_resolver'
    bref.messenger.eventbridge_client:
        class: AsyncAws\EventBridge\EventBridgeClient

